const localImagesList = {
  email: require("../public/assets/email.png"),
  mobile: require("../public/assets/mobile.png"),
  api: require("../public/assets/api.png"),
  cpp: require("../public/assets/cpp.png"),
  css: require("../public/assets/css.png"),
  figma: require("../public/assets/figma.png"),
  flutter: require("../public/assets/flutter.png"),
  git: require("../public/assets/git.png"),
  graphql: require("../public/assets/graphql.png"),
  html: require("../public/assets/html.png"),
  javascript: require("../public/assets/javascript.png"),
  mu5: require("../public/assets/mu5.png"),
  node: require("../public/assets/node.png"),
  python: require("../public/assets/python.png"),
  react: require("../public/assets/react.png"),
  redux: require("../public/assets/redux.png"),
  sass: require("../public/assets/sass.png"),
  typescript: require("../public/assets/typescript.png"),
  vue: require("../public/assets/vue.png"),
  about01: require("../public/assets/about01.png"),
  about02: require("../public/assets/about02.png"),
  about03: require("../public/assets/about03.png"),
  about04: require("../public/assets/about04.png"),
  profile: require("../public/assets/profile.png"),
  circle: require("../public/assets/circle.svg"),
  logo: require("../public/assets/logo.png"),
  adidas: require("../public/assets/adidas.png"),
  amazon: require("../public/assets/amazon.png"),
  asus: require("../public/assets/asus.png"),
  bolt: require("../public/assets/bolt.png"),
  nb: require("../public/assets/nb.png"),
  skype: require("../public/assets/skype.png"),
  spotify: require("../public/assets/spotify.png"),
};

export default localImagesList;
